config/routes.rb
Rails.application.routes.draw do
  devise_for :models
  resources :locations do
    resources :comments
  end
  get 'homepage/index'
  resources :places
  root 'homepage#index'
  get 'police/index'
  get 'news/index'
  resources :contacts, only: [:new, :create]
  get 'search', to: "places#search"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :location
end

app/models/contact.rb
class Contact < MailForm::Base
	attribute :name,   :validate => true
	attribute :message,   :validate => true
	attribute :email,   :validate => /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	
	def headers 
		{
			:subject => "Contact Form",
			:to => "crimeguardapp@gmail.com",
			:from => %("#{name}" <#{email}>)
		}
	end
end
	

app/models/location.rb
class Location < ApplicationRecord
	serialize :image, JSON
	has_many :comments, dependent: :destroy
	has_one_attached :image
	
	validates :address, presence: true
	
	geocoded_by :address
	after_validation :geocode, if: :address_changed?

	def self.search(search)
		if search
			location = Location.find_by(city: search)
			if location
				self.where(id: location)
			else
				Location.all
			end
		else
			Location.all
		end
	end

end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/place.rb
class Place < ApplicationRecord
    def change
        create_table :data do |t|
         t.string :name
         t.string :latitude
         t.string :longitude
         t.timestamps
       end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @location = Location.find(params[:location_id])
        @comment = @location.comments.create(comment_params)
        redirect_to location_path(@location)
    end

    private def comment_params
        params.require(:comment).permit(:username, :body)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def new
		@contact = Contact.new
	end
	
	def create
		@contact = Contact.new(params[:contact])
		@contact.request = request
		if @contact.deliver
			flash.now[:error] = nil
		else
			flash.now[:error] = 'Message cannot be send.'
			render :new
		end
	end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index    
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: %i[ show edit update destroy ]
  before_action :authenticate_model!, only: %i[ edit new ]
  # GET /locations or /locations.json
  def index
    @locations = Location.where(['city LIKE ?', "%#{params[:search]}%"])
  end

  # GET /locations/1 or /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations or /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: "Report Form was successfully created." }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1 or /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: "Report Form was successfully updated." }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1 or /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: "Report Form was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def location_params
      params.require(:location).permit(:address, :city, :typec, :description, :image, :datetime, :latitude, :longitude, :search)
    end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
    news= News.new("7f3dca4f47724527b0737614b76299a2")
    @news = news.get_top_headlines(q: "crime")
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: %i[ show ]

  # GET /places or /places.json
  def index
    @places = Place.where(['name LIKE ?', "%#{params[:search]}%"])
    @crimes = Location.all
  end

  # GET /places/1 or /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # POST /places or /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: "Place was successfully created." }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def place_params
      params.require(:place).permit(:name, :latitude, :longitude)
    end
end

app/controllers/police_controller.rb
class PoliceController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/police_helper.rb
module PoliceHelper
end

app/views/contacts/create.html.erb
<h1 id="page_title">Thank you for your message!</h1><p></p>

<div class="skinny_wrapper wrapper_padding">
	<p> We will get back to you as soon as we can!</p>
</div>

app/views/contacts/new.html.erb
<%= form_with(model: @contact, local: true) do |form| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="main">


  <div class="jumbotron text-center">
      <h1>Contact Form</h1>
  </div>

  <div class="form-group col-5">
    <%= form.label :name, "What is your name?",  class: "col-10 col-form-label"  %>
    <%= form.text_area :name, rows: 1 ,class: "form-control", required: true  %>
  </div>

  <div class="form-group col-5">
    <%= form.label :email, "What is your email?",  class: "col-10 col-form-label"  %>
    <%= form.email_field :email, rows: 1 , class: "form-control", required: true   %>
  </div>

  <div class="form-group col-8">
    <%= form.label :message, "Please write your thoughts here:",  class: "col-10 col-form-label"  %>
    <%= form.text_area :message, rows:5 , class: "form-control", required: true   %>
  </div>

  <br></br>

  <div class="actions">
    <%= form.submit "Send", class: "btn btn-success" %>
  </div>
<% end %>
</div>

<div>
  <div class="card">
    <div class="card-body">
  <p><b>
  Note: the aim of CrimeGuard is to raise awareness of crime in the area. At no point should users use the app as
    a substitute for the real emergency services. If you find yourself or others in danger please at first contact
    the police and/or the emergency services on the following number: </br> <b> 999 </b> (United Kingdom).
</br></br>
    Other numbers you may find useful are as follows:</br>
    101 – The non-emergency number for the police</br>
    111 – The non-emergency medical number</br>
    116 123 - Samaritans if you are struggling with a mental health crisis</br>
    0808 2000 247 - National Domestic Abuse Helpline</b>
  </p>
</div></div>
</div>

app/views/homepage/index.html.erb
<div id="logo" class= "text-center">
<img src="<%= image_url('crimeguardlogo.png')%>" alt="Reponsive image" class="mx-auto d-block img-fluid">
<p class= "text-center"> The app to keep you safe</p>
  <% if !current_model %>
<%= link_to 'Get Started', new_model_session_path, class:"btn btn-outline-primary" %>
  <% end %>
  <%= render 'shared/footer' %>
</div>

app/views/locations/edit.html.erb
<div class="main">


<div class="jumbotron text-center">
  <h1>Editing Location</h1>
</div>


<%= render 'form', location: @location %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<br>
<div class="container">
  <div class="jumbotron text-center">
    <h1>Report Submissions</h1>


<div class="jumbotron text-center">
<%= form_tag(locations_path, method: :get) do %>
    <div class="form-outline input-group">
    <%= text_field_tag(:search, params[:search], placeholder: "Search by city name", class: "form-control") %>
  <%= submit_tag ("Search"), class: "btn btn-outline-success my-2 my-sm-0" %>
  <% end %>
</div></div>
<br>

<% @locations.each do|location| %>
  <div class="card mb-3">
    <% if location.image.attached? %>
        <h5 class="card-title"><%= location.typec %></h5>
        <h6 class="card-text"><%= location.address %></h6><br/>
        <p class="card-text"><%= location.description%></p>
        <p class="card-text"><small class="text-muted"><%= time_ago_in_words(location.datetime) %></small>    <%= location.city %></p>
        <%= link_to 'View', location_path(location), class:"btn btn-outline-info" %>
        <% if current_model && current_model.admin? %>
          <%= link_to 'Edit', edit_location_path(location), class:"btn btn-outline-primary" %>
          <%= link_to 'Delete', location_path(location), class:"btn btn-outline-danger", method: :delete, data:{confirm: "Are you sure?"} %>
        <% end %>
      </div>
    <% else %>
      <div class="card-body">
        <h5 class="card-title"><%= location.typec %></h5>
        <h6 class="card-text"><%= location.address %></h6><br/>
        <p class="card-text"><%= location.description%></p>
        <p class="card-text"><small class="text-muted"><%= time_ago_in_words(location.datetime) %></small>    <%= location.city %></p>
        <%= link_to 'View', location_path(location), class:"btn btn-outline-info" %>
        <% if current_model && current_model.admin? %>
          <%= link_to 'Edit', edit_location_path(location), class:"btn btn-outline-primary" %>
          <%= link_to 'Delete', location_path(location), class:"btn btn-outline-danger", method: :delete, data:{confirm: "Are you sure?"} %>
        <% end %>
    <% end %>
    </div>
  </div>
<% end %>
<%= link_to 'New Form', new_location_path, class:"btn btn-secondary" %>

</div>
</div>

app/views/locations/new.html.erb
<div class="main">


<div class="jumbotron text-center">
    <h1>Report Submission Form</h1>
</div>

<%= render 'form', location: @location %>

<%= link_to 'Back', locations_path %>
</div>

app/views/locations/show.html.erb
<div class="main">
<h4> View Report </h4><br/>

  <div class="card mb-3">
    <% if @location.image.attached? %>
      <div class="card-body">
        <h5 class="card-title"><%= @location.typec %></h5>
        <h6 class="card-text"><%= @location.address %></h6><br/>
        <p class="card-text"><%= @location.description%></p>
        <p class="card-text"><small class="text-muted"><%= time_ago_in_words(@location.datetime) %></small>    <%= @location.city %></p>
        <% if current_model && current_model.admin %>  
         <%= link_to 'Edit', edit_location_path(@location), class:"btn btn-outline-primary" %>
          <%= link_to 'Delete', location_path(@location), class:"btn btn-outline-danger", method: :delete, data:{confirm: "Are you sure?"} %>
        <% end %>
        <%= link_to 'Back to all submissions', locations_path, type: "button", class:"btn btn-outline-secondary" %>
      </div>
    <% else %>
    <div class="card-body">
      <h5 class="card-title"><%= @location.typec %></h5>
      <h6 class="card-text"><%= @location.address %></h6><br/>
      <p class="card-text"><%= @location.description%></p>
      <p class="card-text"><small class="text-muted"><%= time_ago_in_words(@location.datetime) %></small>    <%= @location.city %></p>
      <% if current_model && current_model.admin %>
        <%= link_to 'Edit', edit_location_path(@location), class:"btn btn-outline-primary" %>
        <%= link_to 'Delete', location_path(@location), class:"btn btn-outline-danger", method: :delete, data:{confirm: "Are you sure?"} %>
      <% end %>
      <%= link_to 'Back to all submissions', locations_path, type: "button", class:"btn btn-outline-secondary" %>
    </div>
  </div>
  
    <% end %>
    <h3>Comments </h3>
    <% @location.comments.each do |comment|%>
      <div class="well">
        <p><strong><%= comment.username %></strong>: <%= comment.body %></p>
        <small><%= time_ago_in_words(comment.created_at) %> ago </small>
      </div>
    <% end %>
    <hr>

    <h4>Add Comment</h4>
    <%= form_for([@location, @location.comments.build]) do |f| %>
      <p>
        <%= f.label :username%><br>
        <%= f.text_field(:username, {:class => 'form-control', required: true}) %>
      </p>
      <p>
        <%= f.label :body%>
        <%= f.text_field(:body, {:class => 'form-control', required: true}) %>
      </p>
      <p>
        <%= f.submit({:class => 'btn btn-success'})%>
      </p>
      <% end %>
    </div>

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<div class="container center">
  <div class="jumbotron text-center">
    <h1>All Cities</h1>
    <h4>Search for a city</h4>
    <h5>(cities name are listed below the map)<h5>
    <div class="jumbotron text-center">
      <%= form_tag(places_path, method: :get) do %>
          <div class="form-outline input-group center">
              <%= text_field_tag(:search, params[:search], placeholder: "Search by city name", class: "form-control") %>
              <%= submit_tag ("Search"), class: "btn btn-outline-success my-2 my-sm-0" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <br>
  <script>
      function initMap() {
        const myLatlng = { lat: 54.5781, lng: -4.4360 };
        const map = new google.maps.Map(document.getElementById("map"), {
          center: myLatlng,
          zoom: 6.2,
        });
        <% @crimes.each do |x| %>
          new google.maps.Marker({
            position: { lat: <%= x.latitude %>, lng: <%= x.longitude %>},
            map: map,
            title: "Reported Crime"
          });
        <% end %>
        infoWindow = new google.maps.InfoWindow();
        const locationButton = document.createElement("button");
        locationButton.textContent = "Click here to get your current location!";
        locationButton.classList.add("custom-map-control-button");
        map.controls[google.maps.ControlPosition.TOP_CENTER].push(locationButton);
        locationButton.addEventListener("click", () => {
          // Try HTML5 geolocation.
          if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(
              (position) => {
                const pos = {
                  lat: position.coords.latitude,
                  lng: position.coords.longitude,
                };
                infoWindow.setPosition(pos);
                infoWindow.setContent("Location found.");
                infoWindow.open(map);
                map.setCenter(pos);
                map.setZoom(17);
              },
              () => {
                handleLocationError(true, infoWindow, map.getCenter());
              }
            );
          }
        });
        const card = document.getElementById("pac-card");
        const input = document.getElementById("pac-input");
        const biasInputElement = document.getElementById("use-location-bias");
        const strictBoundsInputElement = document.getElementById(
          "use-strict-bounds"
        );
        const options = {
          componentRestrictions: { country: "uk" },
          fields: ["formatted_address", "geometry", "name"],
          origin: map.getCenter(),
          strictBounds: false,
          types: ["establishment"],
        };
        map.controls[google.maps.ControlPosition.TOP_RIGHT].push(card);
        const autocomplete = new google.maps.places.Autocomplete(
          input,
          options
        );
        autocomplete.bindTo("bounds", map);
        const infowindow = new google.maps.InfoWindow();
        const infowindowContent = document.getElementById("infowindow-content");
        infowindow.setContent(infowindowContent);
        const marker = new google.maps.Marker({
          map,
          anchorPoint: new google.maps.Point(0, -29),
        });
        autocomplete.addListener("place_changed", () => {
          infowindow.close();
          marker.setVisible(false);
          const place = autocomplete.getPlace();

          if (!place.geometry || !place.geometry.location) {
            window.alert(
              "No details available for input: '" + place.name + "'"
            );
            return;
          }
          if (place.geometry.viewport) {
            map.fitBounds(place.geometry.viewport);
          } else {
            map.setCenter(place.geometry.location);
            map.setZoom(17);
          }
          marker.setPosition(place.geometry.location);
          marker.setVisible(true);
          infowindowContent.children["place-name"].textContent = place.name;
          infowindowContent.children["place-address"].textContent =
            place.formatted_address;
          infowindow.open(map, marker);
        });

        function setupClickListener(id, types) {
          const radioButton = document.getElementById(id);
          radioButton.addEventListener("click", () => {
            autocomplete.setTypes(types);
            input.value = "";
          });
        }
        setupClickListener("changetype-all", []);
        setupClickListener("changetype-address", ["address"]);
        setupClickListener("changetype-establishment", ["establishment"]);
        setupClickListener("changetype-geocode", ["geocode"]);
        biasInputElement.addEventListener("change", () => {
          if (biasInputElement.checked) {
            autocomplete.bindTo("bounds", map);
          } else {
            // User wants to turn off location bias, so three things need to happen:
            // 1. Unbind from map
            // 2. Reset the bounds to whole world
            // 3. Uncheck the strict bounds checkbox UI (which also disables strict bounds)
            autocomplete.unbind("bounds");
            autocomplete.setBounds({
              east: 180,
              west: -180,
              north: 90,
              south: -90,
            });
            strictBoundsInputElement.checked = biasInputElement.checked;
          }
          input.value = "";
        });
        strictBoundsInputElement.addEventListener("change", () => {
          autocomplete.setOptions({
            strictBounds: strictBoundsInputElement.checked,
          });

          if (strictBoundsInputElement.checked) {
            biasInputElement.checked = strictBoundsInputElement.checked;
            autocomplete.bindTo("bounds", map);
          }
          input.value = "";
        });
        function search() {
          const search = {
            bounds: map.getBounds(),
            types: ["lodging"],
          };
          places.nearbySearch(search, (results, status, pagination) => {
            if (status === google.maps.places.PlacesServiceStatus.OK && results) {
              clearResults();
              clearMarkers();

              // Create a marker for each hotel found, and
              // assign a letter of the alphabetic to each marker icon.
              for (let i = 0; i < results.length; i++) {
                const markerLetter = String.fromCharCode("A".charCodeAt(0) + (i % 26));
                const markerIcon = MARKER_PATH + markerLetter + ".png";
                // Use marker animation to drop the icons incrementally on the map.
                markers[i] = new google.maps.Marker({
                  position: results[i].geometry.location,
                  animation: google.maps.Animation.DROP,
                  icon: markerIcon,
                });
                // If the user clicks a hotel marker, show the details of that hotel
                // in an info window.
                markers[i].placeResult = results[i];
                google.maps.event.addListener(markers[i], "click", showInfoWindow);
                setTimeout(dropMarker(i), i * 100);
                addResult(results[i], i);
              }
            }
          });
        }

        function clearMarkers() {
          for (let i = 0; i < markers.length; i++) {
            if (markers[i]) {
              markers[i].setMap(null);
            }
          }
          markers = [];
        }

        // Set the country restriction based on user input.
        // Also center and zoom the map on the given country.
        function setAutocompleteCountry() {
          const country = document.getElementById("country").value;

          if (country == "all") {
            autocomplete.setComponentRestrictions({ country: [] });
            map.setCenter({ lat: 15, lng: 0 });
            map.setZoom(2);
          } else {
            autocomplete.setComponentRestrictions({ country: country });
            map.setCenter(countries[country].center);
            map.setZoom(countries[country].zoom);
          }
          clearResults();
          clearMarkers();
        }

        function dropMarker(i) {
          return function () {
            markers[i].setMap(map);
          };
        }

        function addResult(result, i) {
          const results = document.getElementById("results");
          const markerLetter = String.fromCharCode("A".charCodeAt(0) + (i % 26));
          const markerIcon = MARKER_PATH + markerLetter + ".png";
          const tr = document.createElement("tr");
          tr.style.backgroundColor = i % 2 === 0 ? "#F0F0F0" : "#FFFFFF";

          tr.onclick = function () {
            google.maps.event.trigger(markers[i], "click");
          };
          const iconTd = document.createElement("td");
          const nameTd = document.createElement("td");
          const icon = document.createElement("img");
          icon.src = markerIcon;
          icon.setAttribute("class", "placeIcon");
          icon.setAttribute("className", "placeIcon");
          const name = document.createTextNode(result.name);
          iconTd.appendChild(icon);
          nameTd.appendChild(name);
          tr.appendChild(iconTd);
          tr.appendChild(nameTd);
          results.appendChild(tr);
        }

        function clearResults() {
          const results = document.getElementById("results");

          while (results.childNodes[0]) {
            results.removeChild(results.childNodes[0]);
          }
        }

        // Get the place details for a hotel. Show the information in an info window,
        // anchored on the marker for the hotel that the user selected.
        function showInfoWindow() {
          const marker = this;
          places.getDetails(
            { placeId: marker.placeResult.place_id },
            (place, status) => {
              if (status !== google.maps.places.PlacesServiceStatus.OK) {
                return;
              }
              infoWindow.open(map, marker);
              buildIWContent(place);
            }
          );
        }

        // Load the place information into the HTML elements used by the info window.
        function buildIWContent(place) {
          document.getElementById("iw-icon").innerHTML =
            '<img class="hotelIcon" ' + 'src="' + place.icon + '"/>';
          document.getElementById("iw-url").innerHTML =
            '<b><a href="' + place.url + '">' + place.name + "</a></b>";
          document.getElementById("iw-address").textContent = place.vicinity;

          if (place.formatted_phone_number) {
            document.getElementById("iw-phone-row").style.display = "";
            document.getElementById("iw-phone").textContent =
              place.formatted_phone_number;
          } else {
            document.getElementById("iw-phone-row").style.display = "none";
          }

          // Assign a five-star rating to the hotel, using a black star ('&#10029;')
          // to indicate the rating the hotel has earned, and a white star ('&#10025;')
          // for the rating points not achieved.
          if (place.rating) {
            let ratingHtml = "";

            for (let i = 0; i < 5; i++) {
              if (place.rating < i + 0.5) {
                ratingHtml += "&#10025;";
              } else {
                ratingHtml += "&#10029;";
              }
              document.getElementById("iw-rating-row").style.display = "";
              document.getElementById("iw-rating").innerHTML = ratingHtml;
            }
          } else {
            document.getElementById("iw-rating-row").style.display = "none";
          }

          // The regexp isolates the first part of the URL (domain plus subdomain)
          // to give a short URL for displaying in the info window.
          if (place.website) {
            let fullUrl = place.website;
            let website = String(hostnameRegexp.exec(place.website));

            if (!website) {
              website = "http://" + place.website + "/";
              fullUrl = website;
            }
            document.getElementById("iw-website-row").style.display = "";
            document.getElementById("iw-website").textContent = website;
          } else {
            document.getElementById("iw-website-row").style.display = "none";
          }
        }
      }
    </script>
  </head>
  <body>
    <div class="pac-card" id="pac-card">
      <div>


        <div id="title">Search for a Specific Location</div>

        <br />

      </div>
      <div id="pac-container" class="col-md-4 ">
        <input id="pac-input"  class="form-control" type="text" placeholder="Enter a location" />
      </div>
    </div>
    <div id="map"></div>
    <div id="infowindow-content">
      <span id="place-name" class="title"></span><br />
      <span id="place-address"></span>
    </div>
    <table class="table table-hover", style="width:90%; margin-left: auto;
    margin-right: auto;">
      <thead>
        <tr class="table-bordered">
          <th>City</th>
          <th colspan="6"></th>
        </tr>
      </thead>

      <tbody>
        <% @places.each do |place| %>
          <tr>
            <td><%= place.name %></td>
            <td><%= link_to 'Show', place %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <!-- Async script executes immediately and must be after any DOM elements used in callback. -->
    <script
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB1FoiNJNZ68f9AtSOmByGJuZ_b8pHLmoQ&callback=initMap&libraries=places&v=weekly"
      async
    ></script>
  </body>
</html>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<% provide :head_tags do %>
  <meta name='turbolinks-visit-control' content='reload'>
  <script>
    document.addEventListener("DOMContentLoaded", function(){
      initMap(<%=@place.latitude%>, <%=@place.longitude%>)
    });
  </script>
<% end %>
<p id="notice"><%= notice %></p>

<p>
  <h1 style="text-align:center"><%= @place.name %></h1>
</p>



<p>
    <div id="map"></div>
</p>

<div class="p-2">
  <%= link_to 'Back', places_path, class:'btn btn-dark'%>
</div>

<h5 class="text-center" id="policeAPI"></h5>

<div class="p-5" id="count" style="display:none;">
  <div class="card mb-3">
    <div class="card-body">
      <div class="stat">
        <p class="card-text" id="asb"></p>
      </div>
      <div class="stat">
        <p class="card-text" id="bike-theft"></p>
      </div>
      <div class="stat">
        <p class="card-text" id="cda"></p>
      </div>
      <div class="stat">
        <p class="card-text" id="drugs"></p>
      </div>
      <div class="stat">
        <p class="card-text" id="ot"></p>
      </div>
      <div class="stat">
      <p class="card-text" id="violent"></p>
      </div>
      <div class="stat">
        <p class="card-text" id="pow"></p>
      </div>
      <div class="stat">
        <p class="card-text" id="shop"></p>
      </div>
      <div class="stat">
        <p class="card-text" id="theft"></p>
      </div>
      <div class="stat">
        <p class="card-text" id="other"></p>
      </div>
      <div class="stat">
        <p class="card-text" id="po"></p>
      </div>
      <div class="stat">
      <p class="card-text" id="vehicle"></p>
      </div>
    </div>
  </div>

  <br>
  
  <select id="category" onChange="sortCategory(this.value)" style="display:none; float: right;">
    <option value="">Select Category...</value>
    <option value="anti-social-behaviour">Anti Social Behaviour</option>
    <option value="bicycle-theft">Bicycle Theft</option>
    <option value="criminal-damage-arson">Criminal Damage Arson</option>
    <option value="drugs">Drugs</option>
    <option value="other-theft">Other Theft</option>
    <option value="possession-of-weapons">Possession of Weapons</option>
    <option value="public-order">Public Order</option>
    <option value="shoplifting">Shoplifting</option>
    <option value="theft-from-the-person">Theft from the Person</option>
    <option value="vehicle-crime">Vehicle Crime</option>
    <option value="violent-crime">Violent Crime</option>
    <option value="other-crime">Other</option>
  </select>

  <br>
  <br>
  

  <table class="table table-bordered table-hover" id="myTable">
    
    <thead class="thead-dark" id="header">
      
    </thead>
    <tbody id="data">

    </tbody>
  </table>
</div>