config/routes.rb
Rails.application.routes.draw do
  devise_for :models
  resources :locations do
    resources :comments
  end
  get 'homepage/index'
  resources :places
  root 'homepage#index'
  get 'police/index'
  get 'news/index'
  resources :contacts, only: [:new, :create]
  get 'search', to: "places#search"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :location
end

app/models/contact.rb
class Contact < MailForm::Base
	attribute :name,   :validate => true
	attribute :message,   :validate => true
	attribute :email,   :validate => /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	
	def headers 
		{
			:subject => "Contact Form",
			:to => "crimeguardapp@gmail.com",
			:from => %("#{name}" <#{email}>)
		}
	end
end
	

app/models/location.rb
class Location < ApplicationRecord
	serialize :image, JSON
	has_many :comments, dependent: :destroy
	has_one_attached :image
	
	validates :address, presence: true
	
	geocoded_by :address
	after_validation :geocode, if: :address_changed?

	def self.search(search)
		if search
			location = Location.find_by(city: search)
			if location
				self.where(id: location)
			else
				Location.all
			end
		else
			Location.all
		end
	end

end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/place.rb
class Place < ApplicationRecord
    def change
        create_table :data do |t|
         t.string :name
         t.string :latitude
         t.string :longitude
         t.timestamps
       end
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @location = Location.find(params[:location_id])
        @comment = @location.comments.create(comment_params)
        redirect_to location_path(@location)
    end

    private def comment_params
        params.require(:comment).permit(:username, :body)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def new
		@contact = Contact.new
	end
	
	def create
		@contact = Contact.new(params[:contact])
		@contact.request = request
		if @contact.deliver
			flash.now[:error] = nil
		else
			flash.now[:error] = 'Message cannot be send.'
			render :new
		end
	end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index    
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
    news= News.new("7f3dca4f47724527b0737614b76299a2")
    @news = news.get_top_headlines(q: "crime")
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: %i[ show ]

  # GET /places or /places.json
  def index
    @places = Place.where(['name LIKE ?', "%#{params[:search]}%"])
    @crimes = Location.all
  end

  # GET /places/1 or /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # POST /places or /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: "Place was successfully created." }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def place_params
      params.require(:place).permit(:name, :latitude, :longitude)
    end
end

app/controllers/police_controller.rb
class PoliceController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/police_helper.rb
module PoliceHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crime Guard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key=AIzaSyB1FoiNJNZ68f9AtSOmByGJuZ_b8pHLmoQ&libraries=places' %>
    <%= javascript_include_tag 'https://unpkg.com/axios/dist/axios.min.js' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield(:head_tags) %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="text-center text-white" style="background-color: #f1f1f1;">
  <div class="text-center text-dark p-3" style="background-color: rgba(0, 0, 0, 0.2);">
crime-guard.herokuapp.com    © 2021 Copyright
    </div></footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" <%= link_to 'Crime Guard', root_path, class: 'navbar-brand' %></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">


        <% if model_signed_in? %>
          <li class="nav-item">
            <a class="nav-link" <%= link_to 'Cities', places_path, class: 'navbar-brand' %></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" <%= link_to 'Submit a Crime', new_location_path, class: 'navbar-brand' %></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" <%= link_to 'Reported Crimes', locations_path, class: 'navbar-brand' %></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" <%= link_to 'Police Stations', police_index_path, class: 'navbar-brand' %></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" <%= link_to 'Crime News', news_index_path, class: 'navbar-brand' %></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" <%= link_to 'Contact Us', new_contact_path, class: 'navbar-brand' %></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" <%= link_to 'Edit Profile', edit_model_registration_path, class: 'navbar-brand' %>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" <%= link_to 'Sign Out', destroy_model_session_path, method: :delete, class: 'navbar_brand' %> </a>
          </li>

        <% else %>
          <li class="nav-item">
            <a class="nav-link" <%= link_to 'Cities', places_path, class: 'navbar-brand' %></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" <%= link_to 'Submit a Crime', new_location_path, class: 'navbar-brand' %></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" <%= link_to 'Reported Crimes', locations_path, class: 'navbar-brand' %></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" <%= link_to 'Police Stations', police_index_path, class: 'navbar-brand' %></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" <%= link_to 'Crime News', news_index_path, class: 'navbar-brand' %></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" <%= link_to 'Contact Us', new_contact_path, class: 'navbar-brand' %></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" <%= link_to 'Sign Up', new_model_registration_path, class: 'navbar-brand' %></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" <%= link_to 'Sign In', new_model_session_path, class: 'navbar-brand' %> </a>
          </li>
        <% end %>






      </ul>
    </div>
  </div>
</nav>